context:
  name: tranche
  version: "0.2.3.post1"

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/${{ name[0] }}/${{ name }}/${{ name }}-${{ version }}.tar.gz
  sha256: 62409a928fe04bd9bb3403dc5730a1553a8b16c3c5e087f41c2a9a23c94a11b7

build:
  script: python -m pip install . -vv --no-deps --no-build-isolation
  number: 0
  noarch: python

requirements:
  host:
    - python ${{ python_min }}.*
    - pip
    - setuptools >=64
  run:
    - python >=${{ python_min }}
    # numpy extra
    - numpy >=1.22


tests:
  - python:
      imports:
        - tranche
      pip_check: true
  - files:
      source:
        - tests/**
    requirements:
      run:
        - python ${{ python_min }}.*
        - pytest >=7.4
        - pytest-cov >=4.1
    script:
      - pytest -q

about:
  homepage: https://github.com/xylar/tranche
  summary: ConfigParser with layered precedence, provenance, and safe expressions
  description: |
    ConfigParser with layered precedence, provenance, comment-preserving
    writes, and safe expressions.

    The name tranche comes from the French word for slice — a nod to how the
    library lets you cut cleanly through multiple configuration layers to get a
    single, effective view of your settings.
  license: BSD-3-Clause
  license_file: LICENSE
  documentation: https://xylar.github.io/tranche
  repository: https://github.com/xylar/tranche

extra:
  recipe-maintainers:
    - xylar
